[build]
  publish = "."            # serves index.html from the repo root

[functions]
  directory = "."          # functions are in the repo root
  node_bundler = "esbuild"
  included_files = ["_shared/**"]   # your helpers folder

[dev]
  port = 8888
  functionsPort = 9999
