[build]
publish = "."                      # serves index.html from repo root

[functions]
directory = "netlify/functions"    # <— point to the real functions folder
node_bundler = "esbuild"
included_files = ["netlify/functions/_shared/**"]  # <— bundle shared helpers

[dev]
port = 8888
functionsPort = 9999
